// AUTO-GENERATED from shared/src/ by scripts/sync-shared-to-mobile.mjs
// DO NOT EDIT this file directly — edit shared/src/ and re-run the sync
// script. The mobile app reads its copy from here because EAS Build
// can't resolve the workspace package on its end.

// @money-nest/shared
// Validation schemas + cross-platform types shared between the Next.js web
// app and the React Native mobile app.
//
// Source of truth for: request bodies, response shapes, category lists.
// Keep ONLY pure code in here (no React, no Mongoose, no DOM/RN imports).

export * from "./validations/transaction";
export * from "./validations/budget";
export * from "./validations/goal";
export * from "./categories";
export * from "./types/api";
