// app.config.ts — Money Nest mobile.
// Extends the SDK 55 scaffold's app.json with the plugins + extra fields
// the app actually needs: SecureStore for JWT, Notifications for push,
// Google Sign-In for native auth, and a few env-driven values.

import type { ExpoConfig } from "expo/config";

const config: ExpoConfig = {
  name: "Money Nest",
  slug: "money-nest",
  version: "0.1.1",
  orientation: "portrait",
  icon: "./assets/images/icon.png",
  scheme: "moneynest",
  userInterfaceStyle: "automatic",
  ios: {
    supportsTablet: true,
    bundleIdentifier: "co.sunlightgroup.moneynest",
    // No iOS-specific `icon` override — the top-level `icon` field
    // (1024×1024 marketing PNG generated by icon.kitchen) is used for
    // every iOS size. The previous `./assets/expo.icon` path was a
    // placeholder for Apple's iOS 18+ Icon Composer bundle, which we
    // don't ship.
  },
  android: {
    package: "co.sunlightgroup.moneynest",
    adaptiveIcon: {
      // White lets the navy "$" mark + blue wings pop against the
      // launcher's circle/squircle mask. icon.kitchen's foreground
      // PNG sits transparent on top of this color.
      backgroundColor: "#ffffff",
      foregroundImage: "./assets/images/android-icon-foreground.png",
      // No `backgroundImage` — icon.kitchen generated an empty/white
      // background PNG, so we let `backgroundColor` alone drive the
      // back layer. Saves one asset and matches what Android themed
      // icons expect anyway.
      monochromeImage: "./assets/images/android-icon-monochrome.png",
    },
    predictiveBackGestureEnabled: false,
  },
  web: {
    output: "static",
    favicon: "./assets/images/favicon.png",
  },
  // Plugins kept Expo-Go-friendly: no native Google Sign-In plugin (the
  // browser-based expo-auth-session flow doesn't need a config plugin and
  // works inside Expo Go without any custom native code).
  plugins: [
    "expo-router",
    [
      "expo-splash-screen",
      {
        backgroundColor: "#4f46e5",
        android: {
          image: "./assets/images/splash-icon.png",
          imageWidth: 76,
        },
      },
    ],
    "expo-secure-store",
    "expo-notifications",
    "expo-web-browser",
    "expo-sharing",
  ],
  experiments: {
    typedRoutes: true,
    // React Compiler is still experimental and has known crashes with
    // NativeWind's className transform. Keep it OFF until we've validated
    // the production build. Re-enable later for the perf win.
    reactCompiler: false,
  },
  extra: {
    // EAS — auto-generated by `eas init`. Required so EAS Build can match
    // the project to https://expo.dev/accounts/codolve/projects/money-nest.
    // Don't edit manually after first run.
    eas: {
      projectId: "d87dbfa8-7ca9-4769-bf01-ab40c6659576",
    },

    // Runtime config read via expo-constants.
    // Override per build with EAS env vars or a local mobile/.env file.

    // Where the JSON API lives (dashboard, transactions, etc.). Default
    // is production so EAS-built APKs (which can't read mobile/.env)
    // still talk to the right backend. Local dev overrides this via
    // mobile/.env when developing against a LAN IP / Android emulator.
    apiBaseUrl:
      process.env.EXPO_PUBLIC_API_BASE_URL ||
      "https://moneynestapp.vercel.app",

    // Where the OAuth relay lives. Must be HTTPS (Google's hard requirement)
    // — typically your prod Vercel URL even during dev, because Google
    // doesn't accept LAN/IP-based redirect URIs on Web OAuth clients.
    authBaseUrl:
      process.env.EXPO_PUBLIC_AUTH_BASE_URL ||
      "https://moneynestapp.vercel.app",
  },
};

export default config;
