// AUTO-GENERATED from shared/src/ by scripts/sync-shared-to-mobile.mjs
// DO NOT EDIT this file directly — edit shared/src/ and re-run the sync
// script. The mobile app reads its copy from here because EAS Build
// can't resolve the workspace package on its end.

import { z } from "zod";

export const budgetPeriods = [
  "Weekly",
  "Monthly",
  "Quarterly",
  "Yearly",
] as const;

export const budgetCategoryNames = [
  "Food",
  "Housing",
  "Transport",
  "Lifestyle",
  "Shopping",
  "Learning",
  "Personal",
  "Salary",
  "Transfer",
  "Other",
] as const;

export const createBudgetSchema = z.object({
  name: z
    .string()
    .min(2, "Budget name must be at least 2 characters")
    .max(50, "Budget name must be at most 50 characters")
    .trim(),
  category: z.enum(budgetCategoryNames, {
    message: "Please select a valid category",
  }),
  allocated: z
    .number({ message: "Allocated amount must be a number" })
    .positive("Allocated amount must be greater than zero"),
  period: z.enum(budgetPeriods, {
    message: "Please select a valid period",
  }),
  startDate: z.string().optional(),
  endDate: z.string().optional(),
});

export const updateBudgetSchema = createBudgetSchema.partial();

export type BudgetPeriod = (typeof budgetPeriods)[number];
export type CreateBudgetInput = z.infer<typeof createBudgetSchema>;
export type UpdateBudgetInput = z.infer<typeof updateBudgetSchema>;
