// AUTO-GENERATED from shared/src/ by scripts/sync-shared-to-mobile.mjs
// DO NOT EDIT this file directly — edit shared/src/ and re-run the sync
// script. The mobile app reads its copy from here because EAS Build
// can't resolve the workspace package on its end.

import { z } from "zod";

export const goalCategories = [
  "Emergency Fund",
  "Vacation",
  "New Car",
  "Home Purchase",
  "Education",
  "Wedding",
  "Other",
] as const;

export const goalPriorities = ["High", "Medium", "Low"] as const;

// NOTE: the web app uses Tailwind classes (e.g. "bg-blue-500") for goal
// colors. Native code should map these to hex via the categoryColor helper
// rather than rendering the class string directly.
export const goalColors = [
  "bg-blue-500",
  "bg-green-500",
  "bg-amber-500",
  "bg-purple-500",
  "bg-red-500",
  "bg-teal-500",
  "bg-pink-500",
] as const;

export const createGoalSchema = z.object({
  name: z
    .string()
    .min(2, "Goal name must be at least 2 characters")
    .max(80, "Goal name must be at most 80 characters")
    .trim(),
  target: z
    .number({ message: "Target amount must be a number" })
    .positive("Target amount must be greater than zero"),
  category: z.enum(goalCategories, {
    message: "Please select a valid category",
  }),
  priority: z.enum(goalPriorities, {
    message: "Please select a valid priority",
  }),
  deadline: z.string().min(1, "Deadline is required"),
  color: z.enum(goalColors, {
    message: "Please select a color",
  }),
});

export const updateGoalSchema = createGoalSchema.partial();

export type GoalCategory = (typeof goalCategories)[number];
export type GoalPriority = (typeof goalPriorities)[number];
export type CreateGoalInput = z.infer<typeof createGoalSchema>;
export type UpdateGoalInput = z.infer<typeof updateGoalSchema>;
