// AUTO-GENERATED from shared/src/ by scripts/sync-shared-to-mobile.mjs
// DO NOT EDIT this file directly — edit shared/src/ and re-run the sync
// script. The mobile app reads its copy from here because EAS Build
// can't resolve the workspace package on its end.

import { z } from "zod";

export const transactionTypes = ["income", "expense", "transfer"] as const;

export const categoryNames = [
  "Food",
  "Housing",
  "Transport",
  "Lifestyle",
  "Shopping",
  "Learning",
  "Personal",
  "Salary",
  "Transfer",
  "Other",
] as const;

const baseTransactionSchema = z.object({
  description: z
    .string()
    .min(2, "Description must be at least 2 characters")
    .max(200, "Description must be at most 200 characters")
    .trim(),
  amount: z
    .number({ message: "Amount must be a number" })
    .positive("Amount must be greater than zero"),
  date: z.string().min(1, "Date is required"),
});

export const incomeTransactionSchema = baseTransactionSchema.extend({
  type: z.literal("income"),
  category: z.enum(categoryNames, {
    message: "Please select a valid category",
  }),
  toAccountId: z.string().min(1, "Please select an account"),
  fromAccountId: z.string().optional(),
});

export const expenseTransactionSchema = baseTransactionSchema.extend({
  type: z.literal("expense"),
  category: z.enum(categoryNames, {
    message: "Please select a valid category",
  }),
  fromAccountId: z.string().min(1, "Please select an account"),
  toAccountId: z.string().optional(),
});

export const transferTransactionSchema = baseTransactionSchema.extend({
  type: z.literal("transfer"),
  fromAccountId: z.string().min(1, "Please select a source account"),
  toAccountId: z.string().min(1, "Please select a destination account"),
  category: z.string().default("Transfer"),
});

export const createTransactionSchema = z.discriminatedUnion("type", [
  incomeTransactionSchema,
  expenseTransactionSchema,
  transferTransactionSchema,
]);

export const updateTransactionSchema = z.object({
  type: z.enum(transactionTypes).optional(),
  description: z
    .string()
    .min(2, "Description must be at least 2 characters")
    .max(200, "Description must be at most 200 characters")
    .trim()
    .optional(),
  amount: z
    .number({ message: "Amount must be a number" })
    .positive("Amount must be greater than zero")
    .optional(),
  date: z.string().min(1, "Date is required").optional(),
  category: z.string().optional(),
  fromAccountId: z.string().optional(),
  toAccountId: z.string().optional(),
});

export type TransactionType = (typeof transactionTypes)[number];
export type CategoryName = (typeof categoryNames)[number];
export type CreateTransactionInput = z.infer<typeof createTransactionSchema>;
export type UpdateTransactionInput = z.infer<typeof updateTransactionSchema>;
